version: '2'
services:
   shiny:
      container_name: airsensor-dataviewer-test
      image: airsensor-dataviewer-test
      ports:
          - "6709:3838"
      volumes:
          - /var/www/html/logs/airsensor-dataviewer/test/app:/var/log/shiny-server/
      restart: unless-stopped

#networks:
#  custom:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.67.09.0/24
#          gateway: 172.67.09.1
