version: '3'
services:
   shiny:
      container_name: airsensor-dataviewer-test
      image: airsensor-dataviewer-test
      ports:
          - "6709:3838"
      volumes:
          - /var/www/tools.mazamascience.com/html/logs/airsensor-dataviewer/test:/var/log/shiny-server
      restart: unless-stopped

